{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/nab/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "import json\n",
    "import logging\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pyeed import Pyeed\n",
    "import matplotlib.pyplot as plt\n",
    "import itertools\n",
    "from pyeed.analysis.embedding_analysis import EmbeddingTool\n",
    "from scipy.spatial.distance import pdist, squareform\n",
    "from neomodel import db\n",
    "import rich"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mdmodels import DataModel\n",
    "from mdmodels.graph import connect_to_neo4j, generate_neomodel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pyeed Graph Object Mapping constraints not defined. Use _install_labels() to set up model constraints.\n",
      "ðŸ“¡ Connected to database.\n",
      "All data has been wiped from the database.\n",
      "Connecting to bolt://neo4j:12345678@127.0.0.1:7687\n",
      "Dropping constraints...\n",
      "\n",
      "Dropping indexes...\n",
      "\n",
      "All constraints and indexes have been removed from the database.\n"
     ]
    }
   ],
   "source": [
    "uri = \"bolt://127.0.0.1:7687\"\n",
    "user = \"neo4j\"\n",
    "password = \"12345678\"\n",
    "\n",
    "eedb = Pyeed(uri, user=user, password=password)\n",
    "\n",
    "eedb.db.wipe_database('2024-12-08')\n",
    "eedb.db.remove_db_constraints(user=user, password=password)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'connect_to_neo4j' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Step 1: Connect to Neo4J\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[43mconnect_to_neo4j\u001b[49m(\n\u001b[1;32m      3\u001b[0m     host\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlocalhost\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      4\u001b[0m     user\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mneo4j\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      5\u001b[0m     password\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m12345678\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      6\u001b[0m     port\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m7687\u001b[39m\n\u001b[1;32m      7\u001b[0m )\n\u001b[1;32m      9\u001b[0m \u001b[38;5;66;03m# Clear the database\u001b[39;00m\n\u001b[1;32m     10\u001b[0m db\u001b[38;5;241m.\u001b[39mcypher_query(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMATCH (n) DETACH DELETE n\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'connect_to_neo4j' is not defined"
     ]
    }
   ],
   "source": [
    "# Step 1: Connect to Neo4J\n",
    "connect_to_neo4j(\n",
    "    host=\"localhost\",\n",
    "    user=\"neo4j\",\n",
    "    password=\"12345678\",\n",
    "    port=7687\n",
    ")\n",
    "\n",
    "# Clear the database\n",
    "db.cypher_query(\"MATCH (n) DETACH DELETE n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "thread '<unnamed>' panicked at src/bindings/python.rs:58:74:\n",
      "called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }\n",
      "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
     ]
    },
    {
     "ename": "PanicException",
     "evalue": "called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPanicException\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Step 2: Generate neomodel types\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m types \u001b[38;5;241m=\u001b[39m \u001b[43mgenerate_neomodel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmodel_pyeed.md\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      3\u001b[0m rich\u001b[38;5;241m.\u001b[39mprint(types)\n",
      "File \u001b[0;32m~/Niklas/py-mdmodels/mdmodels/graph/create.py:56\u001b[0m, in \u001b[0;36mgenerate_neomodel\u001b[0;34m(path, content)\u001b[0m\n\u001b[1;32m     54\u001b[0m     model \u001b[38;5;241m=\u001b[39m DataModel\u001b[38;5;241m.\u001b[39mfrom_markdown_string(content)\u001b[38;5;241m.\u001b[39mmodel\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m path:\n\u001b[0;32m---> 56\u001b[0m     model \u001b[38;5;241m=\u001b[39m \u001b[43mDataModel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfrom_markdown\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mmodel\n\u001b[1;32m     57\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     58\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEither path or content must be provided.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mPanicException\u001b[0m: called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }"
     ]
    }
   ],
   "source": [
    "# Step 2: Generate neomodel types\n",
    "types = generate_neomodel(path=\"model_pyeed.md\")\n",
    "rich.print(types)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 3: Create a new node\n",
    "Molecule = types[\"Molecule\"]\n",
    "Reaction = types[\"Reaction\"]\n",
    "\n",
    "reaction = Reaction(name=\"Reaction\").save()\n",
    "substrate = Molecule(identifier=\"Substrate\", name=\"Substrate\").save()\n",
    "product = Molecule(identifier=\"Product\", name=\"Product\").save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Step 4: Create a relationship\n",
    "reaction.educts.connect(substrate)\n",
    "reaction.products.connect(product)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 5: Add out of schema relationship\n",
    "reaction_2 = Reaction(name=\"Related Reaction\").save()\n",
    "\n",
    "reaction.dyn_connect(reaction_2, \"RELATED\", {\"has_same_kinetics\": True})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pyeed_niklas",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
