{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/nab/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "import json\n",
    "import logging\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pyeed import Pyeed\n",
    "import matplotlib.pyplot as plt\n",
    "import itertools\n",
    "from pyeed.analysis.embedding_analysis import EmbeddingTool\n",
    "from scipy.spatial.distance import pdist, squareform\n",
    "from neomodel import db\n",
    "import rich"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mdmodels import DataModel\n",
    "from mdmodels.graph import connect_to_neo4j, generate_neomodel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pyeed Graph Object Mapping constraints not defined. Use _install_labels() to set up model constraints.\n",
      "ðŸ“¡ Connected to database.\n",
      "All data has been wiped from the database.\n",
      "Connecting to bolt://neo4j:12345678@127.0.0.1:7687\n",
      "Dropping constraints...\n",
      "\n",
      "Dropping indexes...\n",
      "\n",
      "All constraints and indexes have been removed from the database.\n"
     ]
    }
   ],
   "source": [
    "uri = \"bolt://127.0.0.1:7687\"\n",
    "user = \"neo4j\"\n",
    "password = \"12345678\"\n",
    "\n",
    "eedb = Pyeed(uri, user=user, password=password)\n",
    "\n",
    "eedb.db.wipe_database('2024-12-08')\n",
    "eedb.db.remove_db_constraints(user=user, password=password)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'connect_to_neo4j' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Step 1: Connect to Neo4J\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[43mconnect_to_neo4j\u001b[49m(\n\u001b[1;32m      3\u001b[0m     host\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlocalhost\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      4\u001b[0m     user\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mneo4j\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      5\u001b[0m     password\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m12345678\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m      6\u001b[0m     port\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m7687\u001b[39m\n\u001b[1;32m      7\u001b[0m )\n\u001b[1;32m      9\u001b[0m \u001b[38;5;66;03m# Clear the database\u001b[39;00m\n\u001b[1;32m     10\u001b[0m db\u001b[38;5;241m.\u001b[39mcypher_query(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMATCH (n) DETACH DELETE n\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'connect_to_neo4j' is not defined"
     ]
    }
   ],
   "source": [
    "# Step 1: Connect to Neo4J\n",
    "connect_to_neo4j(\n",
    "    host=\"localhost\",\n",
    "    user=\"neo4j\",\n",
    "    password=\"12345678\",\n",
    "    port=7687\n",
    ")\n",
    "\n",
    "# Clear the database\n",
    "db.cypher_query(\"MATCH (n) DETACH DELETE n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "thread '<unnamed>' panicked at src/bindings/python.rs:58:74:\n",
      "called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }\n",
      "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
     ]
    },
    {
     "ename": "PanicException",
     "evalue": "called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPanicException\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Step 2: Generate neomodel types\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m types \u001b[38;5;241m=\u001b[39m \u001b[43mgenerate_neomodel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmodel_pyeed.md\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      3\u001b[0m rich\u001b[38;5;241m.\u001b[39mprint(types)\n",
      "File \u001b[0;32m~/Niklas/py-mdmodels/mdmodels/graph/create.py:56\u001b[0m, in \u001b[0;36mgenerate_neomodel\u001b[0;34m(path, content)\u001b[0m\n\u001b[1;32m     54\u001b[0m     model \u001b[38;5;241m=\u001b[39m DataModel\u001b[38;5;241m.\u001b[39mfrom_markdown_string(content)\u001b[38;5;241m.\u001b[39mmodel\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m path:\n\u001b[0;32m---> 56\u001b[0m     model \u001b[38;5;241m=\u001b[39m \u001b[43mDataModel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfrom_markdown\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mpath\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mmodel\n\u001b[1;32m     57\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     58\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEither path or content must be provided.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mPanicException\u001b[0m: called `Result::unwrap()` on an `Err` value: Validator { is_valid: false, errors: [ValidationError { message: \"Property Relationship is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Description is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Attributes is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property positions is defined more than once.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: DuplicateError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Description has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Description\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property start has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"start\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property end has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"end\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property positions has no type specified.\", object: Some(\"Relationships\"), attribute: Some(\"positions\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Relationship has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Relationship\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property Attributes has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"Attributes\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property ontology_id has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"ontology_id\"), location: \"Global\", error_type: TypeError }, ValidationError { message: \"Property label has no type specified.\", object: Some(\"Ontology\"), attribute: Some(\"label\"), location: \"Global\", error_type: TypeError }] }"
     ]
    }
   ],
   "source": [
    "# Step 2: Generate neomodel types\n",
    "types = generate_neomodel(path=\"model_pyeed.md\")\n",
    "rich.print(types)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 3: Create a new node\n",
    "Molecule = types[\"Molecule\"]\n",
    "Reaction = types[\"Reaction\"]\n",
    "\n",
    "reaction = Reaction(name=\"Reaction\").save()\n",
    "substrate = Molecule(identifier=\"Substrate\", name=\"Substrate\").save()\n",
    "product = Molecule(identifier=\"Product\", name=\"Product\").save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Step 4: Create a relationship\n",
    "reaction.educts.connect(substrate)\n",
    "reaction.products.connect(product)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 5: Add out of schema relationship\n",
    "reaction_2 = Reaction(name=\"Related Reaction\").save()\n",
    "\n",
    "reaction.dyn_connect(reaction_2, \"RELATED\", {\"has_same_kinetics\": True})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "your_secret_value\n"
     ]
    }
   ],
   "source": [
    "from dotenv import load_dotenv\n",
    "import os\n",
    "\n",
    "load_dotenv()  # Load variables from .env\n",
    "secret_key = os.getenv(\"MY_SECRET_KEY\")\n",
    "if secret_key is None:\n",
    "    raise ValueError(\"MY_SECRET_KEY is not set in the .env file.\")\n",
    "print(secret_key)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "ename": "AuthError",
     "evalue": "{code: Neo.ClientError.Security.Unauthorized} {message: The client is unauthorized due to authentication failure.}",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAuthError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[26], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpyeed\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Pyeed\n\u001b[0;32m----> 3\u001b[0m eedb \u001b[38;5;241m=\u001b[39m \u001b[43mPyeed\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mbolt://127.0.0.1:2123\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43muser\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mneo4j\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpassword\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m1234567890\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Niklas/pyeed/src/pyeed/main.py:35\u001b[0m, in \u001b[0;36mPyeed.__init__\u001b[0;34m(self, uri, user, password)\u001b[0m\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__init__\u001b[39m(\n\u001b[1;32m     30\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m     31\u001b[0m     uri: \u001b[38;5;28mstr\u001b[39m,\n\u001b[1;32m     32\u001b[0m     user: \u001b[38;5;28mstr\u001b[39m \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m     33\u001b[0m     password: \u001b[38;5;28mstr\u001b[39m \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m     34\u001b[0m ):\n\u001b[0;32m---> 35\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdb \u001b[38;5;241m=\u001b[39m \u001b[43mDatabaseConnector\u001b[49m\u001b[43m(\u001b[49m\u001b[43muri\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43muser\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpassword\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Niklas/pyeed/src/pyeed/dbconnect.py:15\u001b[0m, in \u001b[0;36mDatabaseConnector.__init__\u001b[0;34m(self, uri, user, password)\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_uri \u001b[38;5;241m=\u001b[39m uri\n\u001b[1;32m     14\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdriver \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_driver(uri, user, password)\n\u001b[0;32m---> 15\u001b[0m \u001b[43mneomodel_db\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mset_connection\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdriver\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdriver\u001b[49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# patch db for neomodel\u001b[39;00m\n\u001b[1;32m     17\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconstraints_exist():\n\u001b[1;32m     18\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\n\u001b[1;32m     19\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPyeed Graph Object Mapping constraints not defined. Use _install_labels() to set up model constraints.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m     20\u001b[0m     )\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:135\u001b[0m, in \u001b[0;36mDatabase.set_connection\u001b[0;34m(self, url, driver)\u001b[0m\n\u001b[1;32m    133\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_database_version \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    134\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_database_edition \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 135\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_update_database_version\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:317\u001b[0m, in \u001b[0;36mDatabase._update_database_version\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    313\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    314\u001b[0m \u001b[38;5;124;03mUpdates the database server information when it is required\u001b[39;00m\n\u001b[1;32m    315\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    316\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 317\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcypher_query\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    318\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mCALL dbms.components() yield versions, edition return versions[0], edition\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\n\u001b[1;32m    319\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    320\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_database_version \u001b[38;5;241m=\u001b[39m results[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m    321\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_database_edition \u001b[38;5;241m=\u001b[39m results[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m1\u001b[39m]\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:83\u001b[0m, in \u001b[0;36mensure_connection.<locals>.wrapper\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mhasattr\u001b[39m(config, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDRIVER\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;129;01mand\u001b[39;00m config\u001b[38;5;241m.\u001b[39mDRIVER:\n\u001b[1;32m     81\u001b[0m         _db\u001b[38;5;241m.\u001b[39mset_connection(driver\u001b[38;5;241m=\u001b[39mconfig\u001b[38;5;241m.\u001b[39mDRIVER)\n\u001b[0;32m---> 83\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:471\u001b[0m, in \u001b[0;36mDatabase.cypher_query\u001b[0;34m(self, query, params, handle_unique, retry_on_session_expire, resolve_objects)\u001b[0m\n\u001b[1;32m    466\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    467\u001b[0m     \u001b[38;5;66;03m# Otherwise create a new session in a with to dispose of it after it has been run\u001b[39;00m\n\u001b[1;32m    468\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdriver\u001b[38;5;241m.\u001b[39msession(\n\u001b[1;32m    469\u001b[0m         database\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_database_name, impersonated_user\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mimpersonated_user\n\u001b[1;32m    470\u001b[0m     ) \u001b[38;5;28;01mas\u001b[39;00m session:\n\u001b[0;32m--> 471\u001b[0m         results, meta \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run_cypher_query\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    472\u001b[0m \u001b[43m            \u001b[49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    473\u001b[0m \u001b[43m            \u001b[49m\u001b[43mquery\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    474\u001b[0m \u001b[43m            \u001b[49m\u001b[43mparams\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    475\u001b[0m \u001b[43m            \u001b[49m\u001b[43mhandle_unique\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    476\u001b[0m \u001b[43m            \u001b[49m\u001b[43mretry_on_session_expire\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    477\u001b[0m \u001b[43m            \u001b[49m\u001b[43mresolve_objects\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    478\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    480\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results, meta\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:509\u001b[0m, in \u001b[0;36mDatabase._run_cypher_query\u001b[0;34m(self, session, query, params, handle_unique, retry_on_session_expire, resolve_objects)\u001b[0m\n\u001b[1;32m    507\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m ConstraintValidationFailed(e\u001b[38;5;241m.\u001b[39mmessage) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01me\u001b[39;00m\n\u001b[1;32m    508\u001b[0m     exc_info \u001b[38;5;241m=\u001b[39m sys\u001b[38;5;241m.\u001b[39mexc_info()\n\u001b[0;32m--> 509\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exc_info[\u001b[38;5;241m1\u001b[39m]\u001b[38;5;241m.\u001b[39mwith_traceback(exc_info[\u001b[38;5;241m2\u001b[39m])\n\u001b[1;32m    510\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m SessionExpired:\n\u001b[1;32m    511\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m retry_on_session_expire:\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neomodel/sync_/core.py:494\u001b[0m, in \u001b[0;36mDatabase._run_cypher_query\u001b[0;34m(self, session, query, params, handle_unique, retry_on_session_expire, resolve_objects)\u001b[0m\n\u001b[1;32m    491\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    492\u001b[0m     \u001b[38;5;66;03m# Retrieve the data\u001b[39;00m\n\u001b[1;32m    493\u001b[0m     start \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[0;32m--> 494\u001b[0m     response: Result \u001b[38;5;241m=\u001b[39m \u001b[43msession\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mquery\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    495\u001b[0m     results, meta \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28mlist\u001b[39m(r\u001b[38;5;241m.\u001b[39mvalues()) \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m response], response\u001b[38;5;241m.\u001b[39mkeys()\n\u001b[1;32m    496\u001b[0m     end \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/work/session.py:302\u001b[0m, in \u001b[0;36mSession.run\u001b[0;34m(self, query, parameters, **kwargs)\u001b[0m\n\u001b[1;32m    299\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_auto_result\u001b[38;5;241m.\u001b[39m_buffer_all()\n\u001b[1;32m    301\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_connection:\n\u001b[0;32m--> 302\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_connect\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_config\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdefault_access_mode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    303\u001b[0m     \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_connection \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    304\u001b[0m cx \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_connection\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/work/session.py:130\u001b[0m, in \u001b[0;36mSession._connect\u001b[0;34m(self, access_mode, **acquire_kwargs)\u001b[0m\n\u001b[1;32m    128\u001b[0m     access_mode \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_config\u001b[38;5;241m.\u001b[39mdefault_access_mode\n\u001b[1;32m    129\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 130\u001b[0m     \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_connect\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    131\u001b[0m \u001b[43m        \u001b[49m\u001b[43maccess_mode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mauth\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_config\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mauth\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43macquire_kwargs\u001b[49m\n\u001b[1;32m    132\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    133\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39mCancelledError:\n\u001b[1;32m    134\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handle_cancellation(message\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_connect\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/work/workspace.py:178\u001b[0m, in \u001b[0;36mWorkspace._connect\u001b[0;34m(self, access_mode, auth, **acquire_kwargs)\u001b[0m\n\u001b[1;32m    169\u001b[0m acquire_kwargs_ \u001b[38;5;241m=\u001b[39m {\n\u001b[1;32m    170\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124maccess_mode\u001b[39m\u001b[38;5;124m\"\u001b[39m: access_mode,\n\u001b[1;32m    171\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtimeout\u001b[39m\u001b[38;5;124m\"\u001b[39m: acquisition_timeout,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    175\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mliveness_check_timeout\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    176\u001b[0m }\n\u001b[1;32m    177\u001b[0m acquire_kwargs_\u001b[38;5;241m.\u001b[39mupdate(acquire_kwargs)\n\u001b[0;32m--> 178\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_connection \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_pool\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43macquire_kwargs_\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    179\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_connection_access_mode \u001b[38;5;241m=\u001b[39m access_mode\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_pool.py:526\u001b[0m, in \u001b[0;36mBoltPool.acquire\u001b[0;34m(self, access_mode, timeout, database, bookmarks, auth, liveness_check_timeout)\u001b[0m\n\u001b[1;32m    523\u001b[0m log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m[#0000]  _: <POOL> acquire direct connection, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    524\u001b[0m           \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124maccess_mode=\u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[38;5;124m, database=\u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, access_mode, database)\n\u001b[1;32m    525\u001b[0m deadline \u001b[38;5;241m=\u001b[39m Deadline\u001b[38;5;241m.\u001b[39mfrom_timeout_or_deadline(timeout)\n\u001b[0;32m--> 526\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_acquire\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    527\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mauth\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdeadline\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mliveness_check_timeout\u001b[49m\n\u001b[1;32m    528\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_pool.py:313\u001b[0m, in \u001b[0;36mIOPool._acquire\u001b[0;34m(self, address, auth, deadline, liveness_check_timeout)\u001b[0m\n\u001b[1;32m    308\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m ClientError(\n\u001b[1;32m    309\u001b[0m                 \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfailed to obtain a connection from the pool within \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    310\u001b[0m                 \u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{!r}\u001b[39;00m\u001b[38;5;124ms (timeout)\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(deadline\u001b[38;5;241m.\u001b[39moriginal_timeout)\n\u001b[1;32m    311\u001b[0m             )\n\u001b[1;32m    312\u001b[0m log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m[#0000]  _: <POOL> trying to hand out new connection\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m--> 313\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mconnection_creator\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_pool.py:163\u001b[0m, in \u001b[0;36mIOPool._acquire_new_later.<locals>.connection_creator\u001b[0;34m()\u001b[0m\n\u001b[1;32m    161\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    162\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 163\u001b[0m         connection \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mopener\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    164\u001b[0m \u001b[43m            \u001b[49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mauth\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpool_config\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mauth\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdeadline\u001b[49m\n\u001b[1;32m    165\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    166\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m ServiceUnavailable:\n\u001b[1;32m    167\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdeactivate(address)\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_pool.py:500\u001b[0m, in \u001b[0;36mBoltPool.open.<locals>.opener\u001b[0;34m(addr, auth_manager, deadline)\u001b[0m\n\u001b[1;32m    499\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mopener\u001b[39m(addr, auth_manager, deadline):\n\u001b[0;32m--> 500\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mBolt\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    501\u001b[0m \u001b[43m        \u001b[49m\u001b[43maddr\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mauth_manager\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mauth_manager\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdeadline\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdeadline\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    502\u001b[0m \u001b[43m        \u001b[49m\u001b[43mrouting_context\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpool_config\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpool_config\u001b[49m\n\u001b[1;32m    503\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_bolt.py:488\u001b[0m, in \u001b[0;36mBolt.open\u001b[0;34m(cls, address, auth_manager, deadline, routing_context, pool_config)\u001b[0m\n\u001b[1;32m    486\u001b[0m connection\u001b[38;5;241m.\u001b[39msocket\u001b[38;5;241m.\u001b[39mset_deadline(deadline)\n\u001b[1;32m    487\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 488\u001b[0m     \u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mhello\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    489\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    490\u001b[0m     connection\u001b[38;5;241m.\u001b[39msocket\u001b[38;5;241m.\u001b[39mset_deadline(\u001b[38;5;28;01mNone\u001b[39;00m)\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_bolt5.py:574\u001b[0m, in \u001b[0;36mBolt5x2.hello\u001b[0;34m(self, dehydration_hooks, hydration_hooks)\u001b[0m\n\u001b[1;32m    572\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlogon(dehydration_hooks, hydration_hooks)\n\u001b[1;32m    573\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msend_all()\n\u001b[0;32m--> 574\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfetch_all\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    575\u001b[0m check_supported_server_product(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mserver_info\u001b[38;5;241m.\u001b[39magent)\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_bolt.py:864\u001b[0m, in \u001b[0;36mBolt.fetch_all\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    862\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mresponses[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m    863\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m response\u001b[38;5;241m.\u001b[39mcomplete:\n\u001b[0;32m--> 864\u001b[0m     detail_delta, summary_delta \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfetch_message\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    865\u001b[0m     detail_count \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m detail_delta\n\u001b[1;32m    866\u001b[0m     summary_count \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m summary_delta\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_bolt.py:850\u001b[0m, in \u001b[0;36mBolt.fetch_message\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    846\u001b[0m \u001b[38;5;66;03m# Receive exactly one message\u001b[39;00m\n\u001b[1;32m    847\u001b[0m tag, fields \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39minbox\u001b[38;5;241m.\u001b[39mpop(\n\u001b[1;32m    848\u001b[0m     hydration_hooks\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mresponses[\u001b[38;5;241m0\u001b[39m]\u001b[38;5;241m.\u001b[39mhydration_hooks\n\u001b[1;32m    849\u001b[0m )\n\u001b[0;32m--> 850\u001b[0m res \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_process_message\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtag\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfields\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    851\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39midle_since \u001b[38;5;241m=\u001b[39m monotonic()\n\u001b[1;32m    852\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m res\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_bolt5.py:369\u001b[0m, in \u001b[0;36mBolt5x0._process_message\u001b[0;34m(self, tag, fields)\u001b[0m\n\u001b[1;32m    367\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_server_state_manager\u001b[38;5;241m.\u001b[39mstate \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbolt_states\u001b[38;5;241m.\u001b[39mFAILED\n\u001b[1;32m    368\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 369\u001b[0m     \u001b[43mresponse\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mon_failure\u001b[49m\u001b[43m(\u001b[49m\u001b[43msummary_metadata\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43m{\u001b[49m\u001b[43m}\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    370\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (ServiceUnavailable, DatabaseUnavailable):\n\u001b[1;32m    371\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpool:\n",
      "File \u001b[0;32m~/anaconda3/envs/pyeed_niklas/lib/python3.12/site-packages/neo4j/_sync/io/_common.py:281\u001b[0m, in \u001b[0;36mLogonResponse.on_failure\u001b[0;34m(self, metadata)\u001b[0m\n\u001b[1;32m    279\u001b[0m handler \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhandlers\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mon_summary\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    280\u001b[0m Util\u001b[38;5;241m.\u001b[39mcallback(handler)\n\u001b[0;32m--> 281\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m Neo4jError\u001b[38;5;241m.\u001b[39mhydrate(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mmetadata)\n",
      "\u001b[0;31mAuthError\u001b[0m: {code: Neo.ClientError.Security.Unauthorized} {message: The client is unauthorized due to authentication failure.}"
     ]
    }
   ],
   "source": [
    "from pyeed import Pyeed\n",
    "\n",
    "eedb = Pyeed('bolt://127.0.0.1:2123', user='neo4j', password='1234567890')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "An error occurred: {code: Neo.ClientError.Security.Unauthorized} {message: The client is unauthorized due to authentication failure.}\n"
     ]
    }
   ],
   "source": [
    "from neo4j import GraphDatabase\n",
    "from neo4j.exceptions import ServiceUnavailable\n",
    "\n",
    "def connect_to_neo4j(uri=\"bolt://localhost:2123\", user=\"neo4j\", password=\"niklasniklaspwtem\"):\n",
    "    try:\n",
    "        # Create the driver\n",
    "        driver = GraphDatabase.driver(uri, auth=(user, password))\n",
    "        \n",
    "        # Verify the connection\n",
    "        with driver.session() as session:\n",
    "            result = session.run(\"RETURN 'Connected!' as message\")\n",
    "            print(result.single()['message'])\n",
    "            \n",
    "        return driver\n",
    "    \n",
    "    except ServiceUnavailable:\n",
    "        print(\"Failed to connect to Neo4j. Make sure the database is running.\")\n",
    "        return None\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {str(e)}\")\n",
    "        return None\n",
    "\n",
    "# Connect to the database\n",
    "driver = connect_to_neo4j(password=\"1234567890\")\n",
    "\n",
    "# Don't forget to close the driver when you're done\n",
    "if driver:\n",
    "    driver.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pyeed_niklas",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
